[project]
name = "docs-reflex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "reflex>=0.7.5",
    "reflex-image-zoom>=0.0.2",
]

[dependency-groups]
dev = [
    "basedpyright>=1.28.5",
    "icecream>=2.1.4",
    "ipython>=9.1.0",
]
